INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (10245,'LRG WAVY KNIT - BACK HEATER',49.00,20,0.3,20,NULL,'yes','The Wavy Knit is constructed of cotton/poly mock twist jersey featuring color blocked panels, print on front panel and back panel with woven label on lower front panel.','Prod1-LRG_WAVY_KNIT.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (10246,'LRG TOUCAN FILL TEE',28.00,25,0.4,20,NULL,'yes','The Toucan Fill Tee is constructed of cotton(30%) and polyester(70%), with a imagem in the center.','Prod2-LRG_TOUCAN_FILL_TEE.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (10140,'LRG WAVY BASKETBALL JERSEY',59.00,10,0.20,5,NULL,'yes','The Wavy Basketball Jersey is constructed of poly mesh/poly jersey featuring color blocked panels with print on front panel and back.','Prod3-LRG_WAVY_BASKETBALL_JERSEY.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (10176,'LRG RC BARS TANK',32.00,25,0.5,5,NULL,'no','The Bars Tee is constructed of cotton/poly mock-twist jersey featuring a print on front panel and left sleeve with woven label on lower front panel.','Prod4-LRG_RC_BARS_TANK.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (10123,'LRG EL ARE NUE TEE',34.00,12,0.3,5,NULL,'no','The El Are Nue Tee is constructed of cotton jersey featuring a print on front panel with LRG tag on hem.','Prod5-LRG_EL_ARE_NUE_TEE.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (30455,'ALDER JACKET',105.00,19,0.3,5,NULL,'yes','For those who travel light, stay prepared with this lightweight shell. Keep it close, and when nature takes its course, you?ll be down to follow. ','Prod6-ALDER_JACKET.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (30325,'DULCEY JACKET',130.00,0,0.3,5,NULL,'no','The term ?rained-out? isn?t in your vocabulary. Welcome whatever nature has in store with this portable, lightweight layer. Throwback rib and leather trims set this style apart from the standard issue shell.','Prod7-DULCEY_JACKET.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (32225,'WILLS JACKET',120.00,14,0.3,5,NULL,'no','Keep the weather out and the warmth in this lightweight, coated canvas jacket. Zip front and warm lining make sure this jacket will take you where you want to go, while embroideries and leather details up the style ante. Part of the Wolfeboro Collection, a line that embraces the traditions of Element while meshing classic style with functionality and the appreciation of simple living.','Prod8-WILLS_JACKET.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (35625,'ZIP HOODIE',55.00,10,0.3,5,NULL,'no',' A curated utilitarian essential. This solid fleece draws legacy style into the classic zip up fleece. Solid zip up fleece hoodie. Contrast exposed zip. Embroidered logo at chest. Kangaroo pockets. 260 gram brushed fleece.60% polyester, 40% cotton.','Prod9-ZIP_HOODIE.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (35215,'BOOM JEANS',70.00,10,0.3,5,NULL,'yes','Get down, get on up and get to the grind. When you need your style to adapt to your active lifestyle, opt for this stretch denim. Colored denim. Stretch denim. Button and zip closure. Embossed patch at back waistband. Woven logo at back right pocket. Regular, tapered fit. 98% cotton, 2% elastane.','Prod10-BOOM_JEANS.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (39925,'OWEN PANT',65.00,15,0.3,5,NULL,'no','Sport signature, tug-free style. An exclusive drawstring waistband provides extra support for life lived in motion. Slim colored denim. 10.5 ounce broken twill. 5-pocket style. Tunneled drawstring at waist for a precise fit. Button and zip closure. Embossed patch at back waistband. Woven logo at back right pocket. Slim tapered fit. 98% cotton, 2% elastane.','Prod11-OWEN_PANT.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (30005,'BOOM B JEANS',70.00,15,0.3,5,NULL,'yes','Get down, get on up and get to the grind. When you need your style to adapt to your active lifestyle, opt for this stretch denim.  Colored denim. Stretch denim. Button and zip closure. Embossed patch at back waistband.Woven logo at back right pocket. Regular, tapered fit.98% cotton, 2% elastane.','Prod12-BOOM_B_JEANS.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (35677,'FREDDIE POLO',50.00,10,0.3,5,NULL,'no','A far-from-preppy polo short sleeve shirt that?s been designed with classic simplicity. A solid body with tonal touches on the sleeve and color and minimal Element logo on the left chest make this ready for whatever. Short sleeve solid polo shirt. Tonal contrasts on the sleeve and collar. Clean, minimal design. Element logo on left chest. 190G PIQUE COTTON 190G. 100% cotton.','Prod13-FREDDIE_POLO.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (35633,'BLAKE POLO',55.00,10,0.3,5,NULL,'yes','Not your everyday boring button knit, this Element polo has been stepped up with a modern allover bamboo print. 100% cotton with a matching pocket on the left chest. Short sleeve polo shirt. Allover tropical bamboo print. Pocket at left chest. 160G Jersey. 100% cotton.','Prod14-BLAKE_POLO.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (35612,'HORREL LS SHIRT',60.00,30,0.3,5,NULL,'no','A 100% cotton denim long sleeve shirt that?s about as vintage Americana work wear as it gets. Rinsed denim fabric means a slightly broken-in, lived-in feel, with classic trims and styling.','Prod15-HORREL_LS_SHIRT.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (35675,'MONTARA SHIRT',90.00,10,0.3,5,NULL,'yes','The Montara denim shirt is a premium design down to the last detail. Supreme quality, expert construction, and style that speaks to the exhibitionist in all of us. When it comes to street wear that inspires, Element always goes the distance. Light weight denim shirt. 100% cotton. Chest pocket','Prod16-MONTARA_SHIRT.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (30095,'HOWLAND PANT',60.00,10,0.3,5,NULL,'no','Colored flex twill cotton pant give stretch in all the right places. Performance FLEX technology allows you to move the way you want comfortably.','Prod17-HOWLAND_PANT.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (32145,'CADET PANT',75.00,10,0.3,5,NULL,'yes','Ready for action or relaxation, this pair delivers performance alongside urban style. A cotton ripstop offers a lightweight feel that won’t drag you down. Relaxed jogger pants. Flat waistband with tunneled drawstring for a precise fit. Cuffed hems. Welt pockets at back. Welt coin pocket at front. Woven logo at back pocket. Straight legs. Heavy wash. Ripstop fabric. 100% cotton.','Prod18-CADET_PANT.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (34444,'OWEN WK SHORTS',55.00,10,0.3,5,NULL,'no','Live life in color. Pre broken-in, this broken twill walkshort injects a dose of unconventional color into your kit. Colored walkshorts. Stretch broken twill.5-pocket style. 98% cotton, 2% elastane.','Prod19-OWEN_WK_SHORTS.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (33434,'BOOM WK SHORTS',60.00,10,0.3,5,NULL,'no','When you mess with the bull, you get the Boom. Stretch bull denim gives this pair supreme durability while staying flexible and soft for optimal maneuverability. Colored denim walkshorts. Stretch denim. Button and zip closure. Embossed patch at back waistband. Woven logo at back right pocket. Slim fit. 10.6 ounce stretch bull denim. 98% cotton, 2% elastane.','Prod20-BOOM_WK_SHORTS.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (39999,'MEN PLUSH TROUSERS',86.00,10,0.3,5,NULL,'no','Men''s plush trousers. Maxi embroidered wording and Franklin logo. 100% cotton. Regular fit.','Prod21-MEN_PLUSH_TROUSERS.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (39985,'MEN SHORTS',62.00,10,0.3,5,NULL,'no','Men''s shorts made of lightweight plush. 100% cotton. Short fit. Drawstring at the waist. Embroidered wording and number.','Prod22-MEN_SHORTS.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (32211,'MEN SLIM FIT STRETCH DENIM JEANS',114.00,10,0.3,5,NULL,'yes','Men''s stretch denim jeans. Long Beach style. Slim fit. 98% cotton, 2% elastane.','Prod23-MEN_SLIM_FIT_STRETCH_DENIM_JEANS.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (39876,'MEN PARKA WHITH HOOD',154.00,10,0.3,5,NULL,'no','Men''s parka with sherpa hood. Outer fabric 65% polyester, 35% cotton; inner fabric 100% cotton. Zip and snap closure. Two front pockets. Classic fit.','Prod24-MEN_PARKA_WITH_HOOD.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (19293,'MEN VARSITY JACKET',144.00,10,0.3,5,NULL,'yes','Men''s Varsity style jacket. Baseball-style collar. Side pockets and front snaps. 65% polyester and 35% cotton outside, 100% cotton inside. Classic fit.','Prod25-MEN_VARSITY_JACKET.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (38899,'MEN SHORT SLEEVE POLO SHIRT',62.00,10,0.3,5,NULL,'no','Men''s piqué short sleeve polo shirt. 100% cotton. Regular fit. Side slits. Sleeve edges with contrast stripes. F&M label appliquéd on the chest','Prod26-MEN_SHORT_SLEEVE_POLO_SHIRT.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (23345,'MEN POLO SHIRT',72.00,10,0.3,5,NULL,'no','Men''s piqué short sleeve polo shirt. 100% cotton. Regular fit. Side slits. Franklin&M embroidered on the chest and chest pocket with floral pattern.','Prod27-MEN_POLO_SHIRT.png');
INSERT INTO Product (code,name,price,stock,weight,discount,discountEnd,featured,description,imagePath) VALUES (36633,'MEN SLEEVE POLO SHIRT',62.00,10,0.3,5,NULL,'no','Men''s piqué short sleeve polo shirt. 100% cotton. Regular fit. Side slits. Sleeve edges with contrast stripes. F&M label appliquéd on the chest.','Prod28-MEN_SLEEVE_POLO_SHIRT.png');

INSERT INTO Person (name,password) VALUES ('Mariotti Mizuna','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Carlitos Nicolia','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Joao Almeida','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Nuno Pinto','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Admin001','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Joao Costa','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Antonio Fonseca','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Joana Tomé','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Tony Madeira','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Liliana Faria','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Joao Postiga','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Pedro Morim','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Carlos Costa','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Mario Carvalho','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Catarina Ferreira','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Paula Santos','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Helena Vieira','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Nadia Albano','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Marta Gomes','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');
INSERT INTO Person (name,password) VALUES ('Pedro Ribeiro','4c8ceb321d8d60fb455f92ce20e88aa90a718c0d');

INSERT INTO Client (idPerson,address,email) VALUES (1,'Rua Carlos Paiao 145','marimizuna@gmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (2,'Largo Sidonio Pais 27','nicolia@slb.com');
INSERT INTO Client (idPerson,address,email) VALUES (3,'Rua Aguca Minhota','johnygato@gmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (4,'Avenida Brasil 702 3ESQ','up200100000@gmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (6,'Travessa da Aldeia','quartz@gmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (7,'Rua das mimosas','at2101@gmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (8,'Avenida Mousinho','joana23@hotmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (9,'Rua S.Joao','tonyM@hotmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (10, 'Rua do Couto','liliF@hotmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (11,'Rua das Aguas','Post@gmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (12,'Rua da Madalena','PedroAgc_8@gmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (13,'Rua do Arsenal','CarlitosMinho@gmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (14,'Rua do Carmo','Mariuuuuuuuu@hotmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (15,'Rua dos Bacalhoeiros','CatFerreira@hotmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (16,'Avenida Ressano Garcia','PS666@hotmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (17,'Rua da Prata','HVNavais@hotmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (18,'Rua de São Mamede','Nadiazinha33@gmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (19,'Rua Cidade de Bolama','MEstela45@gmail.com');
INSERT INTO Client (idPerson,address,email) VALUES (20,'Rua Garret','PRDoxa@gmail.com');

INSERT INTO SystemAdministrator VALUES ((SELECT idPerson FROM Person WHERE name='Admin001'));

INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (1,1,1);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (2,2,5);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (3,3,2);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (4,4,2);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (6,5,1);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (7,6,3);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (8,8,1);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (9,8,1);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (9,9,2);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (9,10,3);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (11,11,2);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (11,12,1);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (11,13,1);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (11,14,1);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (12,15,2);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (13,15,1);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (14,15,4);
INSERT INTO ShoppingCart (idPerson,idProduct,quantity) VALUES (15,15,1);

INSERT INTO Checkout (date,idPerson) VALUES ('2016-04-20',1);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-02-20',2);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-02-15',3);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-03-14',4);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-05-19',6);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-01-1',7);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-01-23',8);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-03-2',9);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-03-17',9);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-04-2',9);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-04-29',11);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-03-12',11);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-03-16',11);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-03-25',11);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-04-25',12);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-04-13',13);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-04-15',14);
INSERT INTO Checkout (date,idPerson) VALUES ('2016-03-1',15);

INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (1,1,49.00,1);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (2,2,140.00,5);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (3,3,118.00,2);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (4,4,64.00,2);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (5,5,34.00,1);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (6,6,105.00,3);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (8,7,130.00,1);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (8,8,120.00,1);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (9,9,55.00,2);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (10,10,70.00,3);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (11,11,65.00,2);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (12,12,70.00,1);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (13,13,55.00,1);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (14,14,55.00,1);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (15,15,60.00,2);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (15,16,60.00,1);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (15,17,60.00,4);
INSERT INTO Purchase (idProduct, idCheckout, price, quantity) VALUES (15,18,60.00,1);

INSERT INTO Rate (idPerson,idProduct,date,rating,title,description) VALUES (1,1,'2016-04-30',5,'Awesome Shirt','Fast delivery,quality assured. Wonderful product');
INSERT INTO Rate (idPerson,idProduct,date,rating,title,description) VALUES (2,2,'2016-04-30',4,NULL,'I loved the product and the professionalism.');
INSERT INTO Rate (idPerson,idProduct,date,rating,title,description) VALUES (6,5,'2016-05-25',5,NULL,'It is definitely a great product to buy.');
INSERT INTO Rate (idPerson,idProduct,date,rating,title,description) VALUES (7,6,'2016-01-4',5,NULL,'Makes up for all the money invested.');
INSERT INTO Rate (idPerson,idProduct,date,rating,title,description) VALUES (9,8,'2016-03-4',5,NULL,'Makes up for all the money invested.');
INSERT INTO Rate (idPerson,idProduct,date,rating,title,description) VALUES (11,11,'2016-05-2',5,NULL,'I''m really happy with this product. Thanks :)');
INSERT INTO Rate (idPerson,idProduct,date,rating,title,description) VALUES (15,15,'2016-03-5',5,'In Love','This product is absolutely spectacular');
INSERT INTO Rate (idPerson,idProduct,date,rating,title,description) VALUES (14,15,'2016-04-18',4,NULL,'this product molds to my body , I love it');
INSERT INTO Rate (idPerson,idProduct,date,rating,title,description) VALUES (13,15,'2016-04-15',4,NULL,'I advise buying this product is wonderful');

INSERT INTO WishList (idPerson,idProduct) VALUES (1,5);
INSERT INTO WishList (idPerson,idProduct) VALUES (4,6);
INSERT INTO WishList (idPerson,idProduct) VALUES (4,2);
INSERT INTO WishList (idPerson,idProduct) VALUES (6,1);
INSERT INTO WishList (idPerson,idProduct) VALUES (1,3);
INSERT INTO WishList (idPerson,idProduct) VALUES (3,8);
INSERT INTO WishList (idPerson,idProduct) VALUES (7,2);
INSERT INTO WishList (idPerson,idProduct) VALUES (9,1);
INSERT INTO WishList (idPerson,idProduct) VALUES (1,14);
INSERT INTO WishList (idPerson,idProduct) VALUES (4,25);
INSERT INTO WishList (idPerson,idProduct) VALUES (4,15);
INSERT INTO WishList (idPerson,idProduct) VALUES (6,16);
INSERT INTO WishList (idPerson,idProduct) VALUES (1,26);
INSERT INTO WishList (idPerson,idProduct) VALUES (3,6);
INSERT INTO WishList (idPerson,idProduct) VALUES (7,24);
INSERT INTO WishList (idPerson,idProduct) VALUES (9,28);

INSERT INTO Tags (name) VALUES ('jacket');
INSERT INTO Tags (name) VALUES ('polo');
INSERT INTO Tags (name) VALUES ('jeans');
INSERT INTO Tags (name) VALUES ('shirt');
INSERT INTO Tags (name) VALUES ('pant');
INSERT INTO Tags (name) VALUES ('tank');
INSERT INTO Tags (name) VALUES ('t-shirt');
INSERT INTO Tags (name) VALUES ('jersey');
INSERT INTO Tags (name) VALUES ('hood');
INSERT INTO Tags (name) VALUES ('lrg');
